# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20171113_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profilepic',
            new_name='profile_pic',
        ),
    ]
