# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storycomment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('date', models.DateTimeField(db_column='Date')),
            ],
            options={
                'db_table': 'StoryComment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tripcomment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('date', models.DateTimeField(db_column='Date')),
            ],
            options={
                'db_table': 'TripComment',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='userprize',
            table='UserPrize',
        ),
    ]
