# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBapp', '0002_auto_20171111_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_pic', models.ImageField(blank=True, max_length=250, null=True, upload_to='profile_pics')),
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
    ]
